import Head from "next/head"
import React from "react"

const Meta: React.FC<{}> = ({}) => {
  return (
    <Head>
      <title>Twitter</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Meta
